[client_server]
hostname = "0.0.0.0"
port     = 7777 
secure   = true
certificate_file     = "./cert.pem"
certificate_key_file = "./key.pem"

[agent_server]
hostname = "0.0.0.0"
port     = 8888
secure   = true
certificate_file     = "./cert.pem"
certificate_key_file = "./key.pem"

[database]
hostname = "localhost"
port     = 5432
username = "anon"
password = "anon"
db_name  = "anon"
db_users = "users"
