[server]
hostname = "0.0.0.0"
port     = 8888
secure   = true
certificate_file     = "./cert.pem"
certificate_key_file = "./key.pem"

[database]
hostname = "localhost"
port     = 5432
username = "cosmin"
password = "cosmin"
db_name  = "cosmin"
